driver:
  name: vagrant
  synced_folders:
    - [".", "/opt/sensu-plugin-omnibus"]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  attributes:
    vagrant: true
    omnibus_sensu:
      publishers:

platforms:
  - name: centos-7
    run_list: yum-epel::default
  - name: centos-7-i386
    run_list: yum-epel::default
  - name: centos-6
    run_list: yum-epel::default
  - name: centos-6-i386
    run_list: yum-epel::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: ubuntu-16.04-i386
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-14.04-i386
    run_list: apt::default

suites:
  - name: default
    run_list:
    - build-essential::default
    - omnibus_sensu::default
