sudo: required

services:
  - docker

env:
  - PLATFORM=ubuntu PLATFORM_VERSION=14.04 PACKAGECLOUD_DISTROS="ubuntu/trusty" KERNEL_ARCH=i386
  - PLATFORM=ubuntu PLATFORM_VERSION=14.04 PACKAGECLOUD_DISTROS="ubuntu/trusty" KERNEL_ARCH=x86_64
  - PLATFORM=centos PLATFORM_VERSION=6 PACKAGECLOUD_DISTROS="el/6" KERNEL_ARCH=i386
  - PLATFORM=centos PLATFORM_VERSION=6 PACKAGECLOUD_DISTROS="el/6" KERNEL_ARCH=x86_64

before_install: ./before-install.sh

script: ./build.sh

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
    - $(ls pkg/* | tr "\n" ":")
