sudo: required

services:
  - docker

env:
  - KERNEL_ARCH=i386 DEB_ARCH=i386 CFLAGS=-m32 LDFLAGS=-m32 CXXFLAGS=-m32 CPPFLAGS=-m32
  - KERNEL_ARCH=x86_64 DEB_ARCH=amd64

#before_install:
#- docker pull centos:6
#- docker pull ubuntu:16.04
#- docker run centos:6 /bin/sh -c "ls -l /etc && cat /etc/redhat-release"
#- docker run ubuntu:16.04 /bin/sh -c "lsb_release -a"

script: ./build.sh

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
    - $(ls pkg/* | tr "\n" ":")
